spring:
  servlet:
    multipart:
      # 开启文件上传
      enabled: true
      # 文件最大大小
      max-file-size: 10MB
# feign配置
feign:
  okhttp:
    # 开启okhttp
    enabled: true
  client:
    config:
      load:
        # 连接超时时间,单位毫秒
        connectTimeout: 10000
        # 读超时时间,单位毫秒
        readTimeout: 600000
        # 日志级别
        loggerLevel: basic